manifest_version = 1

[module]
name = "Daily Music"
id = "daily_music"
description = "Posts your most listened to song every day."
version = "0.0.1"
license = "GNU AGPLv3"
authors = ["Fripe"]
requirements = ["aiohttp"]
